name: Fragments check

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
    branches:
      - main

jobs:
  check-fragment-added:
    if: github.event.pull_request.user.type != 'Bot' && !contains(github.event.pull_request.labels.*.name, 'skip-fragment-check')
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Check if linked to the correct pull request
        run: |
          diff=$(git diff origin/${{ github.base_ref }} HEAD --name-only)
          changelog_fragments=$(echo "$diff" | grep "^.changes/unreleased/.*\.yaml$")
          pr_number=${{ github.event.pull_request.number }}
          found_match=false
          
          for file in $changelog_fragments; do
            if grep -qE "PR: *\"?$pr_number\"?" "$file"; then
              echo "✅ Found PR number $pr_number in $file"
              found_match=true
            fi
          done
          
          if [ "$found_match" = false ]; then
            echo "❌ No matching PR number found in changelog fragments."
            exit 1
          fi

          
